### PR TITLE
fix invalid interpretation of nulls in arrays

### PR DESCRIPTION
**Pull request by bashtanov**
Hi Tomas, please could you have a look at the fix?

### CODE REVIEW

**Comment by tvondra** [comment]
Is there any reason why iterate through the bitmap like this, instead of simply computing the position in the bitmap directly, i.e. something like

int byte = (i / 8);
int bit = (i % 8);

/* if null */
if ((bitmap[byte] & (0x01 << bit)) == 0)
    continue;

Seems simpler and less error-prone than both the old and fixed code.

**Comment by bashtanov** [comment]
Probably this kind iteration is faster, at least it is vastly used in postgres code. We anyway need to iterate in this way through the values, as they may have different length (including zero when null), so there is no way to access postgres array structure by index only.

OTOH your approach is also used, e.g. in `array_get_isnull` function in `arrayfuncs.c`. Probably it'd better to switch to high-level iterator interface from `arrayaccess.h` it it doesn't introduce much overhead. I'm on holiday till 29 August, will investigate more thoroughly later.

**Comment by tvondra** [comment]
Sure, this won't work for the values (mostly because of NULLs, as we only support fixed-length entries). But for the bitmap it would work - you're right the current approach is used in various in-core functions, but it seems unnecessarily complex.

The syntax (i/8) and (i%8) syntax is always correct as it computes the byte/bit positions "from scratch" (only from "i"), and is not susceptible to premature "continue" in the loop etc (which is the root cause of the bug). I'd be surprised if it was any slower.

In any case, have a nice vacation, let's continue after August 29.

**Comment by bashtanov** [comment]
Hi Tomas, I've switched to `i/8` and `i%8` approach, could you have a look please?

**Comment by tvondra** [comment]
Thanks!

**Pull request merged**
